const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  // Idempotency guard: if the database already has content, don't wipe/reseed.
  // This lets the seed run safely on every deploy (it only populates an empty DB).
  // To force a full reset + reseed, run with FORCE_SEED=1.
  const existing = await prisma.location.count();
  if (existing > 0 && process.env.FORCE_SEED !== '1') {
    console.log(`⏩ Database already seeded (${existing} locations) — skipping. Set FORCE_SEED=1 to reseed.`);
    return;
  }

  // Clear all tables
  await prisma.appointment.deleteMany();
  await prisma.contactInquiry.deleteMany();
  await prisma.testimonial.deleteMany();
  await prisma.service.deleteMany();
  await prisma.career.deleteMany();
  await prisma.healthCheckup.deleteMany();
  await prisma.blog.deleteMany();
  await prisma.treatment.deleteMany();
  await prisma.doctor.deleteMany();
  await prisma.speciality.deleteMany();
  await prisma.location.deleteMany();

  console.log('🗑️  Cleared all tables');

  // ====================== LOCATIONS ======================
  const locations = [
    {"name":"Marengo Asia Hospitals, Gurugram","slug":"gurugram","address":"Golf Course Ext Rd, Sushant Lok II, Sector 56, Gurugram, Haryana 122011","phone":"1800-309-4444","beds":"200","description":"A multi-super-speciality tertiary care hospital in Gurugram offering advanced cardiac sciences, neurosciences, oncology, orthopaedics and organ transplant programs.","image":"https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=800&q=80","mapUrl":"","specialities":"Cardiac Sciences, Neurosciences, Cancer Care / Oncology, Orthopaedics & Joint Replacement"},
    {"name":"Marengo Asia Hospitals, Faridabad","slug":"faridabad","address":"Plot No. 1, HUDA Staff Colony, Sector 16, Faridabad, Haryana 121002","phone":"1800-309-2222","beds":"200","description":"A NABH-accredited multi-speciality hospital serving Faridabad and the wider NCR with comprehensive cardiac, ortho, renal and critical care services.","image":"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80","mapUrl":"","specialities":"Cardiac Sciences, Orthopaedics & Joint Replacement, Kidney & Urology, Dermatology"},
    {"name":"Marengo CIMS Hospital, Ahmedabad","slug":"ahmedabad","address":"Off Science City Rd, Sola, Ahmedabad, Gujarat 380060","phone":"1800-309-2222","beds":"350","description":"A leading quaternary care hospital in Ahmedabad known for heart, liver and kidney transplants, advanced oncology and comprehensive critical care.","image":"https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=800&q=80","mapUrl":"","specialities":"Cardiac Sciences, Liver Transplant & Hepatology, Cancer Care / Oncology, Radiology & Imaging"},
    {"name":"Marengo KK Patel Super Speciality Hospital, Bhuj","slug":"bhuj","address":"Bhuj, Gujarat 370001","phone":"1800-309-2222","beds":"100","description":"A super-speciality hospital bringing advanced tertiary care to Bhuj and the Kutch region across multiple medical and surgical disciplines.","image":"https://images.unsplash.com/photo-1586773860418-d3b3da966367?auto=format&fit=crop&w=800&q=80","mapUrl":"","specialities":"Cardiac Sciences, Orthopaedics & Joint Replacement, General Medicine"},
  ];

  for (const loc of locations) {
    await prisma.location.create({ data: loc });
  }
  console.log(`✅ Created ${locations.length} locations`);

  // ====================== SPECIALITIES ======================
  const specialities = [
    { name: 'Cardiac Sciences', slug: 'cardiac-sciences', icon: '❤️', description: 'Comprehensive heart care including interventional cardiology, cardiac surgery, electrophysiology, heart failure management, and heart transplantation.', featured: true },
    { name: 'Neurosciences', slug: 'neurosciences', icon: '🧠', description: 'Advanced brain and spine care including neurosurgery, neurology, neuroradiology, stroke management, and brain tumor surgery.', featured: true },
    { name: 'Cancer Care / Oncology', slug: 'oncology', icon: '🎗️', description: 'Multi-disciplinary cancer treatment including medical oncology, surgical oncology, radiation therapy, immunotherapy, and bone marrow transplant.', featured: true },
    { name: 'Orthopaedics & Joint Replacement', slug: 'orthopaedics', icon: '🦴', description: 'Comprehensive bone and joint care including joint replacement, sports medicine, spine surgery, arthroscopy, and trauma care.', featured: true },
    { name: 'Gastroenterology & GI Surgery', slug: 'gastroenterology', icon: '🫁', description: 'Advanced digestive care including liver transplant, bariatric surgery, endoscopy, IBD management, and GI oncology.', featured: true },
    { name: 'Kidney & Urology', slug: 'nephrology', icon: '🫘', description: 'Complete renal care including kidney transplant, dialysis, robotic urology, stone management, and uro-oncology.', featured: true },
    { name: 'Liver Transplant & Hepatology', slug: 'liver-transplant', icon: '🫀', description: 'One of the largest liver transplant programs globally with living donor and cadaveric liver transplants, hepatobiliary surgery.', featured: true },
    { name: 'Pulmonology & Lung Transplant', slug: 'pulmonology', icon: '🫁', description: 'Advanced respiratory care including lung transplant, interventional pulmonology, sleep medicine, and critical care.', featured: false },
    { name: 'Endocrinology & Diabetes', slug: 'endocrinology', icon: '💉', description: 'Expert management of diabetes, thyroid disorders, hormonal imbalances, osteoporosis, and metabolic conditions.', featured: false },
    { name: 'Rheumatology', slug: 'rheumatology', icon: '🦵', description: 'Specialized treatment for autoimmune diseases, arthritis, lupus, vasculitis, and other connective tissue disorders.', featured: false },
    { name: 'Dermatology', slug: 'dermatology', icon: '🧴', description: 'Complete skin care including cosmetic dermatology, laser treatments, hair transplant, skin cancer, and pediatric dermatology.', featured: false },
    { name: 'ENT (Ear, Nose & Throat)', slug: 'ent', icon: '👂', description: 'Advanced ENT care including cochlear implants, sinus surgery, head & neck oncology, voice disorders, and sleep apnea.', featured: false },
    { name: 'Ophthalmology', slug: 'ophthalmology', icon: '👁️', description: 'Complete eye care including LASIK, cataract surgery, glaucoma management, retina surgery, and pediatric ophthalmology.', featured: false },
    { name: 'Obstetrics & Gynaecology', slug: 'obstetrics-gynaecology', icon: '🤰', description: 'Comprehensive women\'s health including high-risk pregnancies, fertility treatments, gynaec oncology, and minimally invasive surgery.', featured: true },
    { name: 'Paediatrics & Neonatology', slug: 'paediatrics', icon: '👶', description: 'Complete child healthcare including neonatal ICU, pediatric surgery, pediatric cardiology, and developmental pediatrics.', featured: false },
    { name: 'Psychiatry & Behavioural Sciences', slug: 'psychiatry', icon: '🧘', description: 'Mental health services including addiction medicine, geriatric psychiatry, child psychiatry, and psychotherapy.', featured: false },
    { name: 'Robotic Surgery', slug: 'robotic-surgery', icon: '🤖', description: 'India\'s most advanced robotic surgery program using da Vinci Xi systems across cardiac, urological, gynaecological, and GI surgeries.', featured: true },
    { name: 'Organ Transplant', slug: 'organ-transplant', icon: '💝', description: 'Multi-organ transplant program covering heart, liver, kidney, lung, and bone marrow transplants with India\'s best outcomes.', featured: true },
    { name: 'Radiology & Imaging', slug: 'radiology', icon: '📡', description: 'State-of-the-art diagnostic imaging including 3T MRI, PET-CT, 256-slice CT, interventional radiology, and nuclear medicine.', featured: false },
    { name: 'Emergency & Trauma', slug: 'emergency-trauma', icon: '🚑', description: '24/7 emergency and trauma centre with Level-I trauma care, helipad, rapid response teams, and dedicated trauma ICU.', featured: false },
    { name: 'Plastic & Reconstructive Surgery', slug: 'plastic-surgery', icon: '✨', description: 'Cosmetic and reconstructive surgery including microsurgery, burn care, cleft lip/palate repair, and aesthetic procedures.', featured: false },
    { name: 'Dental Sciences', slug: 'dental', icon: '🦷', description: 'Full-spectrum dental care including implantology, orthodontics, maxillofacial surgery, cosmetic dentistry, and periodontics.', featured: false },
    { name: 'Physiotherapy & Rehabilitation', slug: 'physiotherapy', icon: '🏃', description: 'Comprehensive rehabilitation including cardiac rehab, neuro rehab, sports rehabilitation, and post-surgical recovery programs.', featured: false },
    { name: 'Vascular Surgery', slug: 'vascular-surgery', icon: '🩸', description: 'Advanced vascular interventions including aortic aneurysm repair, varicose veins, peripheral artery disease, and dialysis access.', featured: false },
    { name: 'Nuclear Medicine', slug: 'nuclear-medicine', icon: '☢️', description: 'Diagnostic and therapeutic nuclear medicine including PET-CT, thyroid treatment, bone scans, and targeted radionuclide therapy.', featured: false },
    { name: 'Pain Management', slug: 'pain-management', icon: '💊', description: 'Multidisciplinary pain clinic offering interventional pain procedures, nerve blocks, spinal cord stimulation, and chronic pain management.', featured: false },
    { name: 'Clinical Nutrition & Dietetics', slug: 'clinical-nutrition', icon: '🥗', description: 'Personalized nutrition therapy for diabetes, kidney disease, cancer, weight management, and post-surgical recovery.', featured: false },
    { name: 'Internal Medicine', slug: 'internal-medicine', icon: '🩺', description: 'Comprehensive general medicine covering complex diagnostic challenges, infectious diseases, and multisystem disorders.', featured: false },
    { name: 'Anaesthesiology & Critical Care', slug: 'anaesthesiology', icon: '🏥', description: 'Advanced anaesthesia services, ICU management, ventilator support, sepsis management, and post-operative care.', featured: false },
    { name: 'Mental Health & Wellness', slug: 'mental-health', icon: '🧠', description: 'Integrated mental health services including counselling, stress management, corporate wellness, and de-addiction programs.', featured: false },
  ];

  for (const spec of specialities) {
    await prisma.speciality.create({ data: spec });
  }
  console.log(`✅ Created ${specialities.length} specialities`);

  // ====================== DOCTORS (45 doctors) ======================
  const doctors = [
    {"name":"Dr. Aakriti Aggarwal","slug":"dr-aakriti-aggarwal","speciality":"Obstetrics & Gynaecology","location":"Marengo Asia Hospitals, Gurugram","experience":"8+ Years","qualification":"","designation":"Group Head – Medical Genetics & Genetic Counselling","imageUrl":"/doctors/dr-aakriti-aggarwal.jpg","about":"Group Head – Medical Genetics & Genetic Counselling. Foetal Medicine & Medical Genetics specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":true},
    {"name":"Dr. (Air Cmde) Krishan Kumar Yadav","slug":"dr-krishan-kumar-yadav-neurosurgeon-gurugram","speciality":"Neurosciences","location":"Marengo Asia Hospitals, Gurugram","experience":"35+ Years","qualification":"","designation":"Professor & Clinical Director- Neurosurgery & Neurospine Surgery","imageUrl":"/doctors/dr-krishan-kumar-yadav-neurosurgeon-gurugram.png","about":"Professor & Clinical Director- Neurosurgery & Neurospine Surgery. Neurosurgery specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":true},
    {"name":"Dr. (Brig) Anil Kumar Dhar","slug":"dr-brig-anil-kumar-dhar-oncologist-gurugram","speciality":"Cancer Care / Oncology","location":"Marengo Asia Hospitals, Gurugram","experience":"35+ Years","qualification":"","designation":"Clinical Director and Head - Medical Oncology","imageUrl":"/doctors/dr-brig-anil-kumar-dhar-oncologist-gurugram.jpg","about":"Clinical Director and Head - Medical Oncology. Cancer Care / Oncology specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Abhishek Kumar Gupta","slug":"dr-abhishek-kumar-gupta-physiotherapist-gurugram","speciality":"Physiotherapy & Rehabilitation","location":"Marengo Asia Hospitals, Gurugram","experience":"15+ Years","qualification":"","designation":"HOD - Physiotherapy","imageUrl":"/doctors/dr-abhishek-kumar-gupta-physiotherapist-gurugram.jpg","about":"HOD - Physiotherapy. Physiotherapy and Rehabilitation Medicine specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Bhanu Madan","slug":"dr-bhanu-madan-dentist-gurugram","speciality":"ENT (Ear, Nose & Throat)","location":"Marengo Asia Hospitals, Gurugram","experience":"21+ Years","qualification":"","designation":"Senior Consultant - Dental Department Implantologist, Maxillofacial Prosthodontist","imageUrl":"/doctors/dr-bhanu-madan-dentist-gurugram.png","about":"Senior Consultant - Dental Department Implantologist, Maxillofacial Prosthodontist. Dental specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Dheeraj Gupta","slug":"dr-dheeraj-gupta-eye-specialist-gurugram","speciality":"Ophthalmology","location":"Marengo Asia Hospitals, Gurugram","experience":"26+ Years","qualification":"","designation":"Senior Consultant – Ophthalmology","imageUrl":"/doctors/dr-dheeraj-gupta-eye-specialist-gurugram.jpg","about":"Senior Consultant – Ophthalmology. Eye Care / Ophthalmology specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Diksha Goyal","slug":"dr-diksha-goyal-general-physician-gurugram","speciality":"General Medicine","location":"Marengo Asia Hospitals, Gurugram","experience":"6+ Years","qualification":"","designation":"Consultant - Internal Medicine","imageUrl":"/doctors/dr-diksha-goyal-general-physician-gurugram.png","about":"Consultant - Internal Medicine. Internal Medicine specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Indrajit Agrawal","slug":"dr-indrajit-agrawal-rheumatologist-gurugram","speciality":"Rheumatology","location":"Marengo Asia Hospitals, Gurugram","experience":"25+ Years","qualification":"","designation":"Clinical Director - Rheumatology","imageUrl":"/doctors/dr-indrajit-agrawal-rheumatologist-gurugram.png","about":"Clinical Director - Rheumatology. Rheumatology specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Kripesh Chaubey","slug":"dr-kripesh-chaubey","speciality":"Kidney & Urology","location":"Marengo Asia Hospitals, Gurugram","experience":"5+ Years","qualification":"","designation":"Associate Consultant - Urology & Renal Transplant","imageUrl":"/doctors/dr-kripesh-chaubey.png","about":"Associate Consultant - Urology & Renal Transplant. Urology and Renal Transplantation specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Neeraj Gupta","slug":"dr-neeraj-gupta-pulmonologist-gurugram","speciality":"Pulmonology & Lung Transplant","location":"Marengo Asia Hospitals, Gurugram","experience":"20+ Years","qualification":"","designation":"Clinical Director: Pulmonology, Respiratory Critical Care & Sleep Medicine","imageUrl":"/doctors/dr-neeraj-gupta-pulmonologist-gurugram.png","about":"Clinical Director: Pulmonology, Respiratory Critical Care & Sleep Medicine. Pulmonology specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Pallavi Vasal","slug":"dr-pallavi-vasal-gynaecologist-gurugram","speciality":"Obstetrics & Gynaecology","location":"Marengo Asia Hospitals, Gurugram","experience":"16+ Years","qualification":"","designation":"Clinical Director - Obstetrics and Gynaecology","imageUrl":"/doctors/dr-pallavi-vasal-gynaecologist-gurugram.jpg","about":"Clinical Director - Obstetrics and Gynaecology. Obstetrics and Gynaecology specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Pankaj Khatana","slug":"dr-pankaj-khatana-general-physician-gurugram","speciality":"General Medicine","location":"Marengo Asia Hospitals, Gurugram","experience":"10+ Years","qualification":"","designation":"Senior Consultant, Internal Medicine","imageUrl":"/doctors/dr-pankaj-khatana-general-physician-gurugram.png","about":"Senior Consultant, Internal Medicine. General Medicine specialist at Marengo Asia Hospitals, Gurugram.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Aashish Amar","slug":"dr-aashish-amar-eye-specialist-faridabad","speciality":"Ophthalmology","location":"Marengo Asia Hospitals, Faridabad","experience":"21+ Years","qualification":"","designation":"Senior Consultant - Ophthalmology","imageUrl":"/doctors/dr-aashish-amar-eye-specialist-faridabad.jpg","about":"Senior Consultant - Ophthalmology. Eye Care / Ophthalmology specialist at Marengo Asia Hospitals, Faridabad.","languages":"English, Hindi","featured":true},
    {"name":"Dr. Anil K V Minz","slug":"dr-anil-k-v-minz-dermatologist-faridabad","speciality":"Dermatology","location":"Marengo Asia Hospitals, Faridabad","experience":"20+ Years","qualification":"","designation":"Sr. Consultant – Dermatology","imageUrl":"/doctors/dr-anil-k-v-minz-dermatologist-faridabad.jpg","about":"Sr. Consultant – Dermatology. Dermatology specialist at Marengo Asia Hospitals, Faridabad.","languages":"English, Hindi","featured":true},
    {"name":"Dr. Anurag Aggarwal","slug":"dr-anurag-aggarwal-joint-replacement-surgeon-faridabad","speciality":"Orthopaedics & Joint Replacement","location":"Marengo Asia Hospitals, Faridabad","experience":"16+ Years","qualification":"","designation":"Program Clinical Director - Orthopaedics & Joint Replacement","imageUrl":"/doctors/dr-anurag-aggarwal-joint-replacement-surgeon-faridabad.png","about":"Program Clinical Director - Orthopaedics & Joint Replacement. Orthopaedics & Joint Replacement specialist at Marengo Asia Hospitals, Faridabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Bharat Nair","slug":"dr-bharat-nair-liver-transplant-surgeon-faridabad","speciality":"Liver Transplant & Hepatology","location":"Marengo Asia Hospitals, Faridabad","experience":"10+ Years","qualification":"","designation":"Consultant - Liver Transplant and Biliary Sciences","imageUrl":"/doctors/dr-bharat-nair-liver-transplant-surgeon-faridabad.jpg","about":"Consultant - Liver Transplant and Biliary Sciences. Liver Transplant and Biliary Sciences specialist at Marengo Asia Hospitals, Faridabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Bir Singh Sehrawat","slug":"dr-bir-singh-sehrawat-gastroenterologist-faridabad","speciality":"Gastroenterology & GI Surgery","location":"Marengo Asia Hospitals, Faridabad","experience":"16+ Years","qualification":"","designation":"Program Clinical Director & HOD - Gastroenterology","imageUrl":"/doctors/dr-bir-singh-sehrawat-gastroenterologist-faridabad.jpg","about":"Program Clinical Director & HOD - Gastroenterology. Gastroenterology specialist at Marengo Asia Hospitals, Faridabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Deepali Gaur","slug":"dr-deepali-gaur-paediatrician-faridabad","speciality":"Paediatrics & Neonatology","location":"Marengo Asia Hospitals, Faridabad","experience":"13+ Years","qualification":"","designation":"Consultant - Paediatrics","imageUrl":"/doctors/dr-deepali-gaur-paediatrician-faridabad.jpg","about":"Consultant - Paediatrics. Neonatology specialist at Marengo Asia Hospitals, Faridabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Jaya Sukul","slug":"dr-jaya-sukul-psychologist-faridabad","speciality":"Psychiatry & Behavioural Sciences","location":"Marengo Asia Hospitals, Faridabad","experience":"12+ Years","qualification":"","designation":"Consultant & HOD - Clinical Psychology","imageUrl":"/doctors/dr-jaya-sukul-psychologist-faridabad.jpg","about":"Consultant & HOD - Clinical Psychology. Clinical Psychology specialist at Marengo Asia Hospitals, Faridabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Kapil Chauhan","slug":"dr-kapil-chauhan-physiotherapist-faridabad","speciality":"Physiotherapy & Rehabilitation","location":"Marengo Asia Hospitals, Faridabad","experience":"15+ Years","qualification":"","designation":"HOD","imageUrl":"/doctors/dr-kapil-chauhan-physiotherapist-faridabad.jpg","about":"HOD. Physiotherapy and Rehabilitation Medicine specialist at Marengo Asia Hospitals, Faridabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Manisha Chakrabarti","slug":"dr-manisha-chakrabarti-cardiologist-faridabad","speciality":"Cardiac Sciences","location":"Marengo Asia Hospitals, Faridabad","experience":"23+ Years","qualification":"","designation":"Senior Consultant - Paediatric Cardiology","imageUrl":"/doctors/dr-manisha-chakrabarti-cardiologist-faridabad.png","about":"Senior Consultant - Paediatric Cardiology. Cardiac Sciences specialist at Marengo Asia Hospitals, Faridabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Ajay Kumar Jain","slug":"dr-ajay-kumar-jain-pulmonologist-ahmedabad","speciality":"Emergency & Trauma","location":"Marengo CIMS Hospital, Ahmedabad","experience":"25+ Years","qualification":"","designation":"Consultant Pulmonologist, Bronchoscopist, Sleep Disorders Specialist & Critical Care Specialist Fellow Medical Thoracoscopy (Greece)","imageUrl":"/doctors/dr-ajay-kumar-jain-pulmonologist-ahmedabad.png","about":"Consultant Pulmonologist, Bronchoscopist, Sleep Disorders Specialist & Critical Care Specialist Fellow Medical Thoracoscopy (Greece). Critical Care specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":true},
    {"name":"Dr. Anand Bhanupriya","slug":"dr-anand-bhanupriya-radiologist-ahmedabad","speciality":"Radiology & Imaging","location":"Marengo CIMS Hospital, Ahmedabad","experience":"7+ Years","qualification":"","designation":"Consultant - Radiologist","imageUrl":"/doctors/dr-anand-bhanupriya-radiologist-ahmedabad.jpg","about":"Consultant - Radiologist. Radiology specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":true},
    {"name":"Dr. Ankit D Patel","slug":"dr-ankit-d-patel","speciality":"Pulmonology & Lung Transplant","location":"Marengo CIMS Hospital, Ahmedabad","experience":"4+ Years","qualification":"","designation":"Consultant – Interventional Pulmonology & Critical Care Medicine","imageUrl":"/doctors/dr-ankit-d-patel.jpg","about":"Consultant – Interventional Pulmonology & Critical Care Medicine. Pulmonology specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Bhavesh B Parekh","slug":"dr-bhavesh-b-parekh-oncologist-ahmedabad","speciality":"Cancer Care / Oncology","location":"Marengo CIMS Hospital, Ahmedabad","experience":"2+ Years","qualification":"","designation":"Head - Medical Oncology","imageUrl":"/doctors/dr-bhavesh-b-parekh-oncologist-ahmedabad.jpg","about":"Head - Medical Oncology. Cancer Care / Oncology specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Bhavesh Thakkar","slug":"dr-bhavesh-thakkar-gastroenterologist-ahmedabad","speciality":"Gastroenterology & GI Surgery","location":"Marengo CIMS Hospital, Ahmedabad","experience":"13+ Years","qualification":"","designation":"Consultant - Gastroenterologist","imageUrl":"/doctors/dr-bhavesh-thakkar-gastroenterologist-ahmedabad.jpg","about":"Consultant - Gastroenterologist. Gastroenterology specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Chintan Sheth","slug":"dr-chintan-sheth-critical-care-specialist-ahmedabad","speciality":"Cardiac Sciences","location":"Marengo CIMS Hospital, Ahmedabad","experience":"10+ Years","qualification":"","designation":"Consultant - Anaesthesiologist and Critical Care Specialist","imageUrl":"/doctors/dr-chintan-sheth-critical-care-specialist-ahmedabad.jpg","about":"Consultant - Anaesthesiologist and Critical Care Specialist. Cardiac Sciences specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Chirag Solanki","slug":"dr-chirag-solanki-neurosurgeon-ahmedabad","speciality":"Neurosciences","location":"Marengo CIMS Hospital, Ahmedabad","experience":"11+ Years","qualification":"","designation":"Consultant Neurosurgeon (Stereotactic & Functional Neurosurgery Specialist)","imageUrl":"/doctors/dr-chirag-solanki-neurosurgeon-ahmedabad.jpg","about":"Consultant Neurosurgeon (Stereotactic & Functional Neurosurgery Specialist). Neurosciences specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Harsh Vyas","slug":"dr-harsh-vyas-foot-and-ankle-surgeon-ahmedabad","speciality":"Orthopaedics & Joint Replacement","location":"Marengo CIMS Hospital, Ahmedabad","experience":"3+ Years","qualification":"","designation":"Consultant Foot and Ankle Surgeon","imageUrl":"/doctors/dr-harsh-vyas-foot-and-ankle-surgeon-ahmedabad.jpg","about":"Consultant Foot and Ankle Surgeon. Orthopaedics & Joint Replacement specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Hitesh Desai","slug":"dr-hitesh-desai-nephrologist-ahmedabad","speciality":"Kidney & Urology","location":"Marengo CIMS Hospital, Ahmedabad","experience":"1+ Years","qualification":"","designation":"Consultant - Nephrologist","imageUrl":"/doctors/dr-hitesh-desai-nephrologist-ahmedabad.jpg","about":"Consultant - Nephrologist. Nephrology specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Jitendra Patel","slug":"dr-jitendra-patel-medicine-diabetologist-ahmedabad","speciality":"Endocrinology & Diabetes","location":"Marengo CIMS Hospital, Ahmedabad","experience":"32+ Years","qualification":"","designation":"Clinical Director - Medicine & Diabetology","imageUrl":"/doctors/dr-jitendra-patel-medicine-diabetologist-ahmedabad.jpg","about":"Clinical Director - Medicine & Diabetology. Diabetes specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Mitesh Chandarana","slug":"dr-mitesh-chandarana-neurologist-ahmedabad","speciality":"Neurosciences","location":"Marengo CIMS Hospital, Ahmedabad","experience":"2+ Years","qualification":"","designation":"Consultant - Neurologist, Parkinson’s & Movement Disorders Specialist","imageUrl":"/doctors/dr-mitesh-chandarana-neurologist-ahmedabad.png","about":"Consultant - Neurologist, Parkinson’s & Movement Disorders Specialist. Neurology specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Mona Patel","slug":"dr-mona-patel-gynaecologist-menopause-specialist-ahmedabad","speciality":"Obstetrics & Gynaecology","location":"Marengo CIMS Hospital, Ahmedabad","experience":"26+ Years","qualification":"","designation":"Senior Consultant - Gynaecologist & Menopause Specialist","imageUrl":"/doctors/dr-mona-patel-gynaecologist-menopause-specialist-ahmedabad.jpg","about":"Senior Consultant - Gynaecologist & Menopause Specialist. Obstetrics and Gynaecology specialist at Marengo CIMS Hospital, Ahmedabad.","languages":"English, Hindi","featured":false},
    {"name":"Dr. Amit Chandan","slug":"dr-amit-chandan-cardiac-surgeon-ahmedabad","speciality":"Cardiac Sciences","location":"Marengo KK Patel Super Speciality Hospital, Bhuj","experience":"12+ Years","qualification":"","designation":"Director - Minimal Invasive & Robotic Cardiac Surgery","imageUrl":"/doctors/dr-amit-chandan-cardiac-surgeon-ahmedabad.jpg","about":"Director - Minimal Invasive & Robotic Cardiac Surgery. Cardiac Sciences specialist at Marengo KK Patel Super Speciality Hospital, Bhuj.","languages":"English, Hindi","featured":true},
    {"name":"Dr. Maulik Bhensdadia","slug":"dr-maulik-bhensdadia-radiation-oncologist-ahmedabad","speciality":"Cancer Care / Oncology","location":"Marengo KK Patel Super Speciality Hospital, Bhuj","experience":"11+ Years","qualification":"","designation":"Consultant - Radiation Oncologist","imageUrl":"/doctors/dr-maulik-bhensdadia-radiation-oncologist-ahmedabad.png","about":"Consultant - Radiation Oncologist. Cancer Care / Oncology specialist at Marengo KK Patel Super Speciality Hospital, Bhuj.","languages":"English, Hindi","featured":true},
    {"name":"Dr. Hiren Kevadiya","slug":"dr-hiren-kevadiya-cardiologist-ahmedabad","speciality":"Cardiac Sciences","location":"Marengo KK Patel Super Speciality Hospital, Bhuj","experience":"4+ Years","qualification":"","designation":"Cardiologist & Cardiac Electrophysiologist","imageUrl":"/doctors/dr-hiren-kevadiya-cardiologist-ahmedabad.jpg","about":"Cardiologist & Cardiac Electrophysiologist. Cardiac Sciences specialist at Marengo KK Patel Super Speciality Hospital, Bhuj.","languages":"English, Hindi","featured":false},
  ];

  for (const doc of doctors) {
    await prisma.doctor.create({ data: doc });
  }
  console.log(`✅ Created ${doctors.length} doctors`);

  // ====================== TREATMENTS (20) ======================
  const treatments = [
    { name: 'Coronary Artery Bypass Grafting (CABG)', slug: 'cabg', speciality: 'Cardiac Sciences', description: 'Heart bypass surgery to restore blood flow to heart muscles.', overview: 'CABG is a surgical procedure that creates new routes for blood to flow around blocked coronary arteries, restoring adequate blood supply to the heart muscle. Marengo Asia Hospitals has performed over 25,000 CABG surgeries with outcomes matching the best global centres.', symptoms: 'Chest pain (angina), shortness of breath, fatigue during physical activity, heart palpitations, dizziness', causes: 'Coronary artery disease caused by plaque buildup (atherosclerosis), high cholesterol, smoking, diabetes, hypertension, family history', diagnosis: 'ECG, Echocardiography, Coronary Angiography, CT Coronary Angiogram, Stress Test, Blood Tests', treatmentOptions: 'Open-heart bypass surgery, Minimally invasive CABG, Off-pump (beating heart) surgery, Robotic-assisted CABG' },
    { name: 'Coronary Angioplasty & Stenting', slug: 'coronary-angioplasty', speciality: 'Cardiac Sciences', description: 'Minimally invasive procedure to open blocked arteries using balloon and stent.', overview: 'Coronary angioplasty (PCI) is a minimally invasive procedure where a balloon catheter is used to open blocked or narrowed coronary arteries, and a stent is placed to keep the artery open. Marengo Asia Hospitals performs over 8,000 angioplasties annually.', symptoms: 'Chest pain, shortness of breath, arm or jaw pain, fatigue, irregular heartbeat', causes: 'Atherosclerosis, coronary artery disease, blood clots, lifestyle factors', diagnosis: 'Cardiac catheterization, Coronary angiography, ECG, Stress test, CT angiography', treatmentOptions: 'Balloon angioplasty, Drug-eluting stent placement, Bioresorbable stents, Rotational atherectomy' },
    { name: 'Heart Transplant', slug: 'heart-transplant', speciality: 'Cardiac Sciences', description: 'Replacement of a failing heart with a healthy donor heart.', overview: 'Heart transplantation is a life-saving surgical procedure for patients with end-stage heart failure. Marengo Asia Hospitals runs one of India\'s most successful heart transplant programs.', symptoms: 'Severe heart failure, cardiomyopathy, irreversible heart damage, LVAD dependency', causes: 'Dilated cardiomyopathy, ischemic heart disease, congenital heart defects, valvular disease', diagnosis: 'Complete cardiac evaluation, HLA matching, psychological assessment, financial counselling', treatmentOptions: 'Orthotopic heart transplant, Combined heart-lung transplant, LVAD as bridge therapy' },
    { name: 'Brain Tumour Surgery', slug: 'brain-tumour-surgery', speciality: 'Neurosciences', description: 'Surgical removal of brain tumours using advanced neuro-navigation.', overview: 'Brain tumour surgery at Marengo Asia Hospitals utilizes state-of-the-art neuro-navigation, intraoperative MRI, and awake craniotomy techniques. Our neurosurgeons have treated over 15,000 brain tumours.', symptoms: 'Persistent headaches, seizures, vision changes, personality changes, weakness, nausea', causes: 'Genetic mutations, radiation exposure, family history, immune system disorders', diagnosis: 'MRI Brain with contrast, CT scan, PET scan, Stereotactic biopsy, Neurological examination', treatmentOptions: 'Microsurgical resection, Awake craniotomy, CyberKnife radiosurgery, Gamma Knife, Endoscopic surgery' },
    { name: 'Spine Surgery', slug: 'spine-surgery', speciality: 'Neurosciences', description: 'Advanced surgical treatment for spinal cord and vertebral conditions.', overview: 'Our spine surgery program offers minimally invasive techniques for disc herniations, spinal stenosis, deformity correction, and spinal tumours using robotic navigation and O-arm imaging.', symptoms: 'Back pain, leg weakness, numbness, difficulty walking, bladder dysfunction', causes: 'Disc degeneration, herniated disc, spinal stenosis, trauma, tumours, scoliosis', diagnosis: 'MRI Spine, X-ray, CT Myelography, EMG/NCV studies, Bone density scan', treatmentOptions: 'Microdiscectomy, Laminectomy, Spinal fusion, Disc replacement, Robotic spine surgery' },
    { name: 'Robotic Knee Replacement', slug: 'robotic-knee-replacement', speciality: 'Orthopaedics & Joint Replacement', description: 'Precision joint replacement using robotic-arm assisted technology.', overview: 'Robotic knee replacement at Marengo Asia Hospitals uses the MAKO robotic-arm system for unparalleled precision in implant placement, resulting in faster recovery and better long-term outcomes.', symptoms: 'Severe knee pain, stiffness, difficulty walking, swelling, grinding sensation', causes: 'Osteoarthritis, rheumatoid arthritis, post-traumatic arthritis, avascular necrosis', diagnosis: 'X-ray, MRI, CT scan, Blood tests for inflammation, Physical examination', treatmentOptions: 'Total knee replacement, Partial knee replacement, Revision knee replacement, Robotic-arm assisted surgery' },
    { name: 'Liver Transplant', slug: 'liver-transplant', speciality: 'Gastroenterology & GI Surgery', description: 'Replacement of diseased liver with healthy donor liver.', overview: 'Marengo Asia Hospitals runs the largest liver transplant program in the world with over 3,500 transplants and a success rate exceeding 95%. Both living donor and deceased donor transplants are performed.', symptoms: 'Jaundice, abdominal swelling, fatigue, confusion, bleeding, weight loss', causes: 'Cirrhosis, hepatitis B/C, alcoholic liver disease, liver cancer, metabolic liver diseases', diagnosis: 'Liver function tests, CT/MRI abdomen, Liver biopsy, MELD score, Donor evaluation', treatmentOptions: 'Living donor liver transplant, Deceased donor transplant, Auxiliary liver transplant, Split liver transplant' },
    { name: 'Kidney Transplant', slug: 'kidney-transplant', speciality: 'Kidney & Urology', description: 'Surgical transplantation of a healthy kidney from a living or deceased donor.', overview: 'Our kidney transplant program has performed over 2,000 successful transplants including robotic kidney transplants — a world first pioneered at Marengo Asia Hospitals.', symptoms: 'End-stage kidney failure, dialysis dependency, fatigue, swelling, low urine output', causes: 'Diabetes, hypertension, glomerulonephritis, polycystic kidney disease, chronic infections', diagnosis: 'Blood typing, HLA matching, Cross-match testing, Donor evaluation, Full medical workup', treatmentOptions: 'Living donor transplant, Deceased donor transplant, Robotic kidney transplant, ABO-incompatible transplant' },
    { name: 'Robotic Prostatectomy', slug: 'robotic-prostatectomy', speciality: 'Kidney & Urology', description: 'Robotic-assisted removal of the prostate gland for prostate cancer.', overview: 'Robotic radical prostatectomy provides maximum cancer control while preserving urinary continence and sexual function. Our urologists have performed over 3,000 robotic prostatectomies.', symptoms: 'Difficulty urinating, blood in urine, pelvic pain, elevated PSA levels', causes: 'Prostate cancer, genetic predisposition, age, hormonal factors', diagnosis: 'PSA blood test, Digital rectal exam, MRI pelvis, Prostate biopsy, Bone scan', treatmentOptions: 'Robotic radical prostatectomy, Active surveillance, Radiation therapy, Hormone therapy' },
    { name: 'Lung Transplant', slug: 'lung-transplant', speciality: 'Pulmonology & Lung Transplant', description: 'Replacement of diseased lungs with healthy donor lungs.', overview: 'Marengo Asia Hospitals performed India\'s first successful bilateral sequential lung transplant. Our program offers single and bilateral lung transplants for end-stage lung disease.', symptoms: 'Severe breathlessness, oxygen dependency, recurrent infections, pulmonary hypertension', causes: 'Pulmonary fibrosis, COPD, cystic fibrosis, pulmonary hypertension, emphysema', diagnosis: 'Pulmonary function tests, CT chest, Right heart catheterization, 6-minute walk test, Blood gas analysis', treatmentOptions: 'Single lung transplant, Bilateral lung transplant, Heart-lung transplant, ECMO bridge therapy' },
    { name: 'Total Hip Replacement', slug: 'total-hip-replacement', speciality: 'Orthopaedics & Joint Replacement', description: 'Surgical replacement of damaged hip joint with prosthetic implant.', overview: 'Our orthopaedic team performs over 2,000 hip replacement surgeries annually using anterior approach, computer-navigated, and robotic-assisted techniques for optimal outcomes.', symptoms: 'Severe hip pain, stiffness, limited mobility, groin pain, difficulty climbing stairs', causes: 'Osteoarthritis, avascular necrosis, hip fracture, rheumatoid arthritis, dysplasia', diagnosis: 'X-ray pelvis, MRI hip, CT scan, Blood tests, Gait analysis', treatmentOptions: 'Total hip replacement, Partial hip replacement, Hip resurfacing, Revision hip replacement' },
    { name: 'Bone Marrow Transplant', slug: 'bone-marrow-transplant', speciality: 'Cancer Care / Oncology', description: 'Transplantation of healthy stem cells to replace diseased bone marrow.', overview: 'Our bone marrow transplant unit is one of India\'s largest, performing over 200 transplants annually for blood cancers, aplastic anemia, and inherited blood disorders.', symptoms: 'Fatigue, frequent infections, abnormal bleeding, anaemia, bone pain', causes: 'Leukaemia, lymphoma, multiple myeloma, aplastic anemia, thalassemia, sickle cell disease', diagnosis: 'Blood tests, Bone marrow biopsy, HLA typing, Genetic testing, PET-CT scan', treatmentOptions: 'Autologous transplant, Allogeneic transplant, Haploidentical transplant, Cord blood transplant' },
    { name: 'TAVR (Transcatheter Aortic Valve Replacement)', slug: 'tavr', speciality: 'Cardiac Sciences', description: 'Minimally invasive valve replacement without open-heart surgery.', overview: 'TAVR is a catheter-based procedure to replace a diseased aortic valve without traditional open-heart surgery. Ideal for high-risk patients. Over 1,000 TAVR procedures performed at Marengo Asia Hospitals.', symptoms: 'Chest pain, fainting, shortness of breath, fatigue, heart murmur, ankle swelling', causes: 'Aortic valve stenosis, calcification, congenital bicuspid valve, rheumatic heart disease', diagnosis: 'Echocardiography, CT aortography, Cardiac catheterization, Calcium scoring', treatmentOptions: 'TAVR, Surgical aortic valve replacement, Balloon valvuloplasty, Medical management' },
    { name: 'Bariatric / Weight Loss Surgery', slug: 'bariatric-surgery', speciality: 'Gastroenterology & GI Surgery', description: 'Surgical treatment for obesity and metabolic disorders.', overview: 'Our bariatric surgery program offers laparoscopic and robotic weight loss surgeries with comprehensive pre and post-operative support for sustained weight management.', symptoms: 'Morbid obesity (BMI>40), obesity-related comorbidities, failed medical weight loss', causes: 'Genetic factors, metabolic disorders, lifestyle, hormonal imbalances', diagnosis: 'BMI calculation, Endocrine evaluation, Sleep study, Nutritional assessment, Psychological evaluation', treatmentOptions: 'Laparoscopic sleeve gastrectomy, Roux-en-Y gastric bypass, Mini gastric bypass, Revision surgery' },
    { name: 'Cochlear Implant', slug: 'cochlear-implant', speciality: 'ENT (Ear, Nose & Throat)', description: 'Electronic device surgically placed to restore hearing in severe deafness.', overview: 'Cochlear implantation at Marengo Asia Hospitals provides hearing restoration for profoundly deaf children and adults using the latest multichannel implant technology.', symptoms: 'Profound hearing loss, inability to hear with hearing aids, speech development delay in children', causes: 'Congenital deafness, meningitis, ototoxic drugs, age-related hearing loss, head trauma', diagnosis: 'Pure tone audiometry, ABR/BERA, CT temporal bone, MRI inner ear, Speech evaluation', treatmentOptions: 'Cochlear implantation, Auditory brainstem implant, Bone-anchored hearing aid, Speech therapy' },
    { name: 'IVF & Fertility Treatment', slug: 'ivf-fertility', speciality: 'Obstetrics & Gynaecology', description: 'Advanced assisted reproduction techniques for infertility treatment.', overview: 'Our IVF centre offers world-class fertility treatments with a success rate of over 55%. We provide comprehensive infertility evaluation and personalized treatment protocols.', symptoms: 'Inability to conceive after 1 year of trying, irregular periods, recurrent miscarriages', causes: 'PCOS, endometriosis, tubal factor, male factor infertility, age-related, unexplained', diagnosis: 'Hormone tests, HSG, Semen analysis, Ovarian reserve testing, Laparoscopy', treatmentOptions: 'IVF, ICSI, IUI, Egg/sperm donation, Surrogacy, Embryo freezing' },
    { name: 'CyberKnife Radiosurgery', slug: 'cyberknife', speciality: 'Cancer Care / Oncology', description: 'Non-invasive robotic radiosurgery for tumours anywhere in the body.', overview: 'CyberKnife is a non-invasive alternative to surgery that delivers precise, high-dose radiation to tumours with sub-millimeter accuracy while sparing surrounding healthy tissue.', symptoms: 'Inoperable tumours, brain metastases, spinal tumours, lung tumours, liver tumours', causes: 'Various cancers requiring precise radiation treatment', diagnosis: 'CT/MRI for treatment planning, PET scan, Fiducial marker placement', treatmentOptions: 'Single-fraction radiosurgery, Multi-fraction radiosurgery, Combined with chemotherapy' },
    { name: 'Robotic Hysterectomy', slug: 'robotic-hysterectomy', speciality: 'Obstetrics & Gynaecology', description: 'Robotic-assisted minimally invasive uterus removal surgery.', overview: 'Robotic hysterectomy offers smaller incisions, less blood loss, less pain, and faster recovery compared to traditional open surgery for uterine conditions.', symptoms: 'Heavy menstrual bleeding, uterine fibroids, endometriosis, uterine prolapse, cervical cancer', causes: 'Fibroids, endometriosis, cancer, adenomyosis, chronic pelvic pain', diagnosis: 'Ultrasound, MRI pelvis, Endometrial biopsy, Pap smear, Hysteroscopy', treatmentOptions: 'Robotic total hysterectomy, Robotic radical hysterectomy, Laparoscopic hysterectomy' },
    { name: 'LASIK Eye Surgery', slug: 'lasik', speciality: 'Ophthalmology', description: 'Laser vision correction surgery to reduce dependency on glasses/contacts.', overview: 'Our ophthalmology department offers bladeless femtosecond LASIK, SMILE, and PRK procedures for precise vision correction using the latest excimer laser technology.', symptoms: 'Myopia, hyperopia, astigmatism, dependency on glasses or contact lenses', causes: 'Refractive errors, corneal shape irregularity', diagnosis: 'Corneal topography, Pachymetry, Wavefront analysis, Dry eye evaluation', treatmentOptions: 'Femto-LASIK, SMILE, PRK, ICL (Implantable Contact Lens)' },
    { name: 'Spinal Cord Stimulation', slug: 'spinal-cord-stimulation', speciality: 'Pain Management', description: 'Implantable device to manage chronic pain through electrical impulses.', overview: 'Spinal cord stimulation therapy delivers mild electrical pulses to the spinal cord to interrupt pain signals, providing significant relief for chronic back pain, neuropathy, and CRPS.', symptoms: 'Chronic back pain, failed back surgery syndrome, neuropathic pain, CRPS', causes: 'Nerve damage, failed spine surgery, diabetic neuropathy, complex regional pain syndrome', diagnosis: 'Comprehensive pain evaluation, MRI, Nerve conduction studies, Trial stimulation', treatmentOptions: 'Dorsal column stimulation, High-frequency stimulation, Burst stimulation, DRG stimulation' },
  ];

  for (const treatment of treatments) {
    await prisma.treatment.create({ data: treatment });
  }
  console.log(`✅ Created ${treatments.length} treatments`);

  // ====================== BLOGS (12) ======================
  const blogs = [
    { title: 'Understanding Heart Attacks: Warning Signs Everyone Should Know', slug: 'understanding-heart-attacks', category: 'Heart Health', author: 'Dr. Praveen Chandra', excerpt: 'Learn to recognize the early warning signs of a heart attack that could save your life or a loved one\'s life.', content: 'A heart attack occurs when blood flow to the heart muscle is blocked. Recognizing early signs can mean the difference between life and death. Warning signs include chest discomfort, shortness of breath, nausea, cold sweat, and pain radiating to the arms, back, or jaw. Women may experience atypical symptoms like extreme fatigue, indigestion, and anxiety. If you suspect a heart attack, call emergency services immediately. Time is muscle — every minute of delay results in more heart muscle damage.', featured: true },
    { title: '10 Foods That Boost Brain Health and Prevent Cognitive Decline', slug: 'brain-health-foods', category: 'Nutrition', author: 'Dr. Vinay Goyal', excerpt: 'Discover the top brain-boosting foods backed by neuroscience research that can help maintain cognitive function.', content: 'Research shows that certain foods can significantly impact brain health. Fatty fish rich in omega-3s, blueberries packed with antioxidants, turmeric with curcumin, broccoli with vitamin K, pumpkin seeds with micronutrients, dark chocolate with flavonoids, nuts especially walnuts, oranges for vitamin C, eggs for choline, and green tea for L-theanine — all support cognitive function and may reduce the risk of neurodegenerative diseases.', featured: false },
    { title: 'Robotic Surgery: How AI Is Transforming Modern Medicine', slug: 'robotic-surgery-ai', category: 'Innovation', author: 'Dr. Sudhir Rawal', excerpt: 'Explore how robotic-assisted surgery is revolutionizing surgical precision, recovery times, and patient outcomes.', content: 'Robotic surgery represents one of the most significant advances in modern medicine. Using the da Vinci Xi surgical system, surgeons can perform complex procedures through tiny incisions with unprecedented precision. Benefits include smaller incisions, less blood loss, reduced pain, shorter hospital stays, and faster recovery. At Marengo Asia Hospitals, we have performed over 10,000 robotic surgeries across multiple specialities.', featured: true },
    { title: 'Managing Diabetes: A Complete Guide for Patients', slug: 'managing-diabetes-guide', category: 'Diabetes Care', author: 'Dr. Ambrish Mithal', excerpt: 'A comprehensive guide to managing Type 1 and Type 2 diabetes, from medication to lifestyle changes.', content: 'Diabetes management requires a holistic approach combining medication, diet, exercise, and monitoring. Key principles include regular blood sugar monitoring, understanding your HbA1c target, medication adherence, carbohydrate counting, regular physical activity (150 minutes/week), foot care, eye screening, kidney function monitoring, and stress management. With proper management, people with diabetes can lead full, healthy lives.', featured: false },
    { title: 'Liver Transplant: When Is It Needed and What to Expect', slug: 'liver-transplant-guide', category: 'Organ Transplant', author: 'Dr. A. S. Soin', excerpt: 'Everything you need to know about liver transplantation — from evaluation to recovery.', content: 'Liver transplantation is recommended when the liver fails to perform its vital functions. Indications include end-stage cirrhosis, acute liver failure, hepatocellular carcinoma, and certain metabolic diseases. The evaluation process involves comprehensive medical, surgical, and psychological assessment. Living donor transplant involves removing a portion of a healthy person\'s liver. Recovery typically takes 3-6 months.', featured: false },
    { title: 'Mental Health Matters: Breaking the Stigma in India', slug: 'mental-health-stigma', category: 'Mental Health', author: 'Dr. Kamna Chhibber', excerpt: 'Understanding why mental health awareness is critical and how to seek help without shame.', content: 'Mental health disorders affect 1 in 7 Indians, yet stigma prevents most from seeking help. Depression, anxiety, and stress-related disorders are treatable conditions, not character weaknesses. Warning signs include persistent sadness, withdrawal from social activities, sleep changes, appetite changes, difficulty concentrating, and thoughts of self-harm. Professional help through therapy and medication can significantly improve quality of life.', featured: false },
    { name: 'Preventing Cancer: Lifestyle Changes That Make a Difference', slug: 'cancer-prevention-lifestyle', category: 'Cancer Care', author: 'Dr. Ashok Vaid', excerpt: 'Evidence-based lifestyle changes that can significantly reduce your risk of developing cancer.', content: 'Up to 40% of cancers can be prevented through lifestyle modifications. Key prevention strategies include not smoking, maintaining a healthy weight, regular exercise, eating a plant-based diet, limiting alcohol, sun protection, getting vaccinated (HPV, Hepatitis B), regular screenings, avoiding processed meats, and managing stress. Early detection through screening is critical for cancers of the breast, cervix, colon, and prostate.', featured: true },
    { title: 'Knee Replacement: Myths vs. Facts', slug: 'knee-replacement-myths', category: 'Orthopaedics', author: 'Dr. Ashok Rajgopal', excerpt: 'Debunking common myths about knee replacement surgery that prevent patients from seeking treatment.', content: 'Common myths: Knee replacement is extremely painful (modern techniques minimize pain), you can never bend your knee again (patients achieve excellent range of motion), replacement joints don\'t last long (modern implants last 20-25 years), surgery should be delayed as long as possible (delayed surgery can worsen outcomes), and only elderly people need it (age is not the determining factor). The reality is that knee replacement can transform quality of life.', featured: false },
    { title: 'Pregnancy Care: Trimester-by-Trimester Guide', slug: 'pregnancy-care-guide', category: 'Women\'s Health', author: 'Dr. Anjali Kumar', excerpt: 'A comprehensive guide to prenatal care, nutrition, and what to expect during each trimester.', content: 'First trimester: confirm pregnancy, start prenatal vitamins, first ultrasound, genetic screening. Second trimester: anatomy scan, gestational diabetes screening, feel baby movements, maternal comfort measures. Third trimester: fetal growth monitoring, birth plan preparation, labor signs awareness, neonatal preparation. Key nutrition includes folic acid, iron, calcium, DHA omega-3s, and adequate protein intake.', featured: false },
    { title: 'Understanding Stroke: Time Is Brain', slug: 'understanding-stroke', category: 'Neurosciences', author: 'Dr. Sumit Singh', excerpt: 'Learn the FAST protocol for stroke recognition and why every minute counts in stroke treatment.', content: 'Stroke is a medical emergency where every minute matters. Use FAST: Face drooping, Arm weakness, Speech difficulty, Time to call emergency. Types include ischemic stroke (blood clot) and hemorrhagic stroke (bleeding). Treatment within 4.5 hours with clot-busting drugs or mechanical thrombectomy can significantly reduce disability. Risk factors include hypertension, diabetes, smoking, atrial fibrillation, and high cholesterol.', featured: false },
    { title: 'The Future of Immunotherapy in Cancer Treatment', slug: 'immunotherapy-cancer', category: 'Cancer Care', author: 'Dr. Ashok Vaid', excerpt: 'How immunotherapy is revolutionizing cancer treatment by harnessing the body\'s own immune system.', content: 'Immunotherapy has transformed cancer treatment by enabling the immune system to recognize and attack cancer cells. Types include checkpoint inhibitors, CAR-T cell therapy, cancer vaccines, and monoclonal antibodies. Marengo Asia Hospitals offers the latest immunotherapy protocols for melanoma, lung cancer, kidney cancer, bladder cancer, and several other malignancies.', featured: false },
    { title: 'Post-COVID Recovery: Long-Term Health Monitoring Guide', slug: 'post-covid-recovery', category: 'General Health', author: 'Dr. Sushila Kataria', excerpt: 'A comprehensive guide to monitoring and managing long-term health effects after COVID-19 recovery.', content: 'Long COVID affects up to 30% of recovered patients. Common symptoms include fatigue, brain fog, shortness of breath, joint pain, and heart palpitations. Recommended monitoring includes pulmonary function tests, cardiac evaluation, blood tests, mental health screening, and rehabilitation exercises. Our post-COVID clinic provides comprehensive evaluation and personalized recovery programs.', featured: false },
  ];

  for (const blog of blogs) {
    const data = { ...blog };
    if (data.name) {
      data.title = data.name;
      delete data.name;
    }
    await prisma.blog.create({ data });
  }
  console.log(`✅ Created ${blogs.length} blogs`);

  // ====================== HEALTH CHECKUPS (10) ======================
  const healthCheckups = [
    { name: 'Vivek Comprehensive Health Screening', slug: 'comprehensive-health-screening', price: '₹12,999', tests: 'Complete Blood Count, Lipid Profile, Liver Function, Kidney Function, Thyroid, HbA1c, Vitamin D, B12, ECG, Chest X-ray, Ultrasound Abdomen, TMT, Pulmonary Function, Eye & Dental Check, Diet Consultation', description: 'Our most comprehensive screening package covering 80+ parameters for complete health assessment.', popular: true },
    { name: 'Vivek Heart Check', slug: 'heart-check', price: '₹8,999', tests: 'Lipid Profile, Apolipoprotein, hs-CRP, Homocysteine, ECG, 2D Echo, TMT, Coronary Calcium Score, Cardiologist Consultation', description: 'Specialized cardiac screening for early detection of heart disease risk factors and hidden heart conditions.', popular: true },
    { name: 'Vivek Cancer Screening (Male)', slug: 'cancer-screening-male', price: '₹15,999', tests: 'PSA, CEA, AFP, CA 19-9, Chest X-ray, Ultrasound Abdomen, Colonoscopy, Low-dose CT Chest, Oncologist Consultation', description: 'Comprehensive cancer screening for men covering prostate, lung, colon, liver, and other common male cancers.', popular: false },
    { name: 'Vivek Cancer Screening (Female)', slug: 'cancer-screening-female', price: '₹16,999', tests: 'CA-125, CA 15-3, CEA, Mammography, Pap Smear, HPV Test, Ultrasound Pelvis, Low-dose CT Chest, Oncologist Consultation', description: 'Comprehensive cancer screening for women covering breast, cervical, ovarian, lung, and colorectal cancers.', popular: false },
    { name: 'Vivek Executive Health Check', slug: 'executive-health-check', price: '₹6,999', tests: 'CBC, Blood Sugar, HbA1c, Lipid Profile, LFT, KFT, Thyroid, Urine Analysis, ECG, Chest X-ray, Physician Consultation', description: 'Essential health check designed for busy professionals, covering all vital health parameters.', popular: true },
    { name: 'Vivek Diabetes Wellness Check', slug: 'diabetes-wellness', price: '₹5,999', tests: 'Fasting Glucose, Post-prandial Glucose, HbA1c, Lipid Profile, KFT, Microalbuminuria, Urine ACR, Fundoscopy, Foot Examination, Endocrinologist Consultation', description: 'Specialized screening for diabetics and pre-diabetics to monitor and prevent diabetes complications.', popular: false },
    { name: 'Vivek Women\'s Wellness', slug: 'womens-wellness', price: '₹9,999', tests: 'CBC, Hormonal Profile, Thyroid, Vitamin D, B12, Iron, Bone Density (DEXA), Mammography, Pap Smear, Pelvic Ultrasound, Gynaecologist Consultation', description: 'Complete women\'s health package covering hormonal, reproductive, and bone health screening.', popular: true },
    { name: 'Vivek Senior Citizen Package', slug: 'senior-citizen-package', price: '₹11,999', tests: 'CBC, Blood Sugar, HbA1c, Lipid Profile, LFT, KFT, Thyroid, PSA/CA-125, ECG, 2D Echo, Chest X-ray, Bone Density, Eye Check, Physician Consultation', description: 'Comprehensive health screening for adults above 60, covering cardiac, metabolic, cancer markers, and bone health.', popular: false },
    { name: 'Vivek Pre-Employment Check', slug: 'pre-employment-check', price: '₹2,999', tests: 'CBC, Blood Sugar, LFT, KFT, Lipid Profile, HIV, HBsAg, Urine Drug Screen, Chest X-ray, ECG, Vision Test', description: 'Standard pre-employment health screening meeting corporate requirements.', popular: false },
    { name: 'Vivek Bone & Joint Assessment', slug: 'bone-joint-assessment', price: '₹7,999', tests: 'Calcium, Phosphorus, Vitamin D, B12, Uric Acid, RA Factor, Anti-CCP, ESR, CRP, Bone Density (DEXA), X-ray Joints, Orthopaedic Consultation', description: 'Comprehensive bone and joint health assessment for early detection of osteoporosis, arthritis, and joint disorders.', popular: false },
  ];

  for (const hc of healthCheckups) {
    await prisma.healthCheckup.create({ data: hc });
  }
  console.log(`✅ Created ${healthCheckups.length} health checkups`);

  // ====================== CAREERS (10) ======================
  const careers = [
    { title: 'Senior Consultant - Cardiology', slug: 'senior-consultant-cardiology', department: 'Cardiac Sciences', location: 'Gurugram', type: 'Full-time', experience: '10-15 years', description: 'Lead clinical practice in interventional cardiology, perform complex PCI procedures, and contribute to the heart failure and transplant programs.', requirements: 'DM (Cardiology), 10+ years post-DM experience, fellowship in interventional cardiology preferred' },
    { title: 'Staff Nurse - ICU', slug: 'staff-nurse-icu', department: 'Nursing', location: 'Gurugram', type: 'Full-time', experience: '2-5 years', description: 'Provide critical care nursing in the adult ICU, manage ventilator patients, and assist in bedside procedures.', requirements: 'B.Sc Nursing or GNM, 2+ years ICU experience, BLS & ACLS certification' },
    { title: 'Radiologist - CT & MRI', slug: 'radiologist-ct-mri', department: 'Radiology', location: 'Noida', type: 'Full-time', experience: '5-8 years', description: 'Interpret CT, MRI, and PET-CT scans across all specialities. Participate in tumor boards and interdisciplinary consultations.', requirements: 'MD (Radiology), 5+ years post-MD experience, fellowship in body imaging preferred' },
    { title: 'Physiotherapist', slug: 'physiotherapist', department: 'Rehabilitation', location: 'Lucknow', type: 'Full-time', experience: '2-4 years', description: 'Provide physiotherapy services for post-surgical, neurological, and orthopaedic rehabilitation patients.', requirements: 'BPT/MPT, 2+ years clinical experience, specialization in neuro or ortho rehab preferred' },
    { title: 'Medical Coder - CPC Certified', slug: 'medical-coder', department: 'Revenue Cycle', location: 'Gurugram', type: 'Full-time', experience: '3-5 years', description: 'Assign ICD-10 and CPT codes for patient encounters, ensure coding accuracy, and support revenue cycle optimization.', requirements: 'CPC or CCS certification, 3+ years medical coding experience, knowledge of ICD-10 and CPT' },
    { title: 'Junior Resident - General Surgery', slug: 'junior-resident-surgery', department: 'General Surgery', location: 'Patna', type: 'Full-time', experience: '0-2 years', description: 'Rotate through general surgery sub-specialities, assist in surgeries, manage ward patients, and participate in academic activities.', requirements: 'MBBS with valid registration, cleared NEET-PG preferred' },
    { title: 'IT Systems Administrator', slug: 'it-systems-admin', department: 'Information Technology', location: 'Gurugram', type: 'Full-time', experience: '5-8 years', description: 'Manage hospital IT infrastructure including HIS, EMR, PACS, and network systems. Ensure 99.9% uptime and data security.', requirements: 'B.Tech/MCA, CCNA/MCSE certification, 5+ years healthcare IT experience' },
    { title: 'Clinical Pharmacist', slug: 'clinical-pharmacist', department: 'Pharmacy', location: 'Indore', type: 'Full-time', experience: '2-4 years', description: 'Provide clinical pharmacy services including medication review, drug interaction checks, antimicrobial stewardship, and patient counselling.', requirements: 'Pharm.D or M.Pharm (Clinical Pharmacy), 2+ years hospital pharmacy experience' },
    { title: 'Patient Care Coordinator', slug: 'patient-care-coordinator', department: 'Patient Services', location: 'Gurugram', type: 'Full-time', experience: '2-3 years', description: 'Coordinate patient journeys from admission to discharge, liaise with clinical teams, and ensure exceptional patient experience.', requirements: 'Graduate degree, 2+ years healthcare coordination experience, excellent communication skills' },
    { title: 'Research Associate - Clinical Trials', slug: 'research-associate-clinical-trials', department: 'Research', location: 'Gurugram', type: 'Full-time', experience: '1-3 years', description: 'Support Phase II-IV clinical trials including patient recruitment, data collection, regulatory documentation, and adverse event reporting.', requirements: 'M.Sc (Life Sciences/Pharmacy), GCP certification, 1+ years clinical research experience' },
  ];

  for (const career of careers) {
    await prisma.career.create({ data: career });
  }
  console.log(`✅ Created ${careers.length} careers`);

  // ====================== SERVICES (15) ======================
  const services = [
    { name: 'Emergency & Trauma Care', slug: 'emergency-trauma-care', category: 'Emergency', description: '24/7 Level-I trauma centre with rapid response teams, helipad, and dedicated trauma ICU. Average door-to-doctor time under 3 minutes.', icon: '🚑' },
    { name: 'Ambulance Service', slug: 'ambulance-service', category: 'Emergency', description: 'Advanced life support ambulances with trained paramedics, cardiac monitors, and ventilators available across Delhi-NCR.', icon: '🏥' },
    { name: 'Diagnostic Laboratory', slug: 'diagnostic-laboratory', category: 'Diagnostics', description: 'NABL-accredited laboratory offering 2000+ tests with same-day reporting. Includes molecular diagnostics and genetic testing.', icon: '🔬' },
    { name: 'Radiology & Imaging Centre', slug: 'radiology-imaging', category: 'Diagnostics', description: 'State-of-the-art imaging with 3T MRI, 256-slice CT, PET-CT, Digital Mammography, Ultrasound, and Interventional Radiology.', icon: '📡' },
    { name: 'Pharmacy Services', slug: 'pharmacy', category: 'Support Services', description: '24/7 in-house pharmacy stocking all essential medications, surgical consumables, and specialized drugs. Home delivery available.', icon: '💊' },
    { name: 'Blood Bank', slug: 'blood-bank', category: 'Support Services', description: 'Licensed blood bank with component separation facility, ensuring safe blood products for surgeries and transfusions.', icon: '🩸' },
    { name: 'Insurance & TPA Desk', slug: 'insurance-tpa', category: 'Financial Services', description: 'Dedicated insurance desk processing cashless claims for 50+ insurance companies and TPAs. Pre-authorization within 2 hours.', icon: '🛡️' },
    { name: 'International Patient Services', slug: 'international-patient-services', category: 'International', description: 'End-to-end support for international patients including visa assistance, airport transfers, language interpreters, and post-treatment follow-up.', icon: '🌍' },
    { name: 'Telemedicine & Video Consultation', slug: 'telemedicine', category: 'Digital Health', description: 'Consult our specialists from anywhere via secure video calls. Available for follow-ups, second opinions, and initial consultations.', icon: '💻' },
    { name: 'Home Healthcare', slug: 'home-healthcare', category: 'Post-Discharge', description: 'Hospital-quality care at home including nursing, physiotherapy, IV therapy, wound care, and doctor visits.', icon: '🏠' },
    { name: 'Rehabilitation & Physiotherapy', slug: 'rehabilitation', category: 'Post-Discharge', description: 'Comprehensive rehabilitation including cardiac rehab, neuro rehab, pulmonary rehab, and post-surgical recovery programs.', icon: '🏃' },
    { name: 'Second Opinion Service', slug: 'second-opinion', category: 'Digital Health', description: 'Get a second opinion from our senior specialists on your diagnosis and treatment plan. Available online and in-person.', icon: '📋' },
    { name: 'Patient Accommodation', slug: 'patient-accommodation', category: 'Support Services', description: 'Premium rooms ranging from deluxe to presidential suites, and nearby guest houses for patient attendants at subsidized rates.', icon: '🛏️' },
    { name: 'Diet & Nutrition Counselling', slug: 'diet-nutrition', category: 'Wellness', description: 'Personalized nutrition plans by certified dietitians for weight management, diabetes, cardiac diet, and pre/post-surgical nutrition.', icon: '🥗' },
    { name: 'Preventive Health Clinic', slug: 'preventive-health-clinic', category: 'Wellness', description: 'Executive health check-ups, cancer screening, cardiac risk assessment, and corporate wellness programs.', icon: '🩺' },
  ];

  for (const service of services) {
    await prisma.service.create({ data: service });
  }
  console.log(`✅ Created ${services.length} services`);

  // ====================== TESTIMONIALS (10) ======================
  const testimonials = [
    { patient: 'Rajesh Kumar', location: 'Delhi, India', content: 'Dr. Naresh Trehan and his cardiac team saved my life with a complex triple bypass surgery. The care and attention I received at Marengo Asia Hospitals was extraordinary. From admission to discharge, every staff member treated me with compassion. The ICU facilities are world-class, and the recovery was smoother than I expected.', rating: 5, featured: true },
    { patient: 'Sarah Thompson', location: 'London, UK', content: 'I travelled from London for a liver transplant at Marengo Asia Hospitals after being told the wait time in the UK would be too long. Dr. A. S. Soin and his team performed the living donor transplant flawlessly. The international patient services team made everything seamless — from visa to accommodation to post-operative care.', rating: 5, featured: true },
    { patient: 'Mohammed Al-Rashid', location: 'Dubai, UAE', content: 'My mother\'s brain tumour was operated on by Dr. Rana Patir with incredible precision. The tumour was in a very delicate location, and many surgeons refused the case. Dr. Patir not only removed the entire tumour but preserved all neurological functions. We are eternally grateful.', rating: 5, featured: true },
    { patient: 'Meera Sharma', location: 'Jaipur, India', content: 'After years of knee pain, I finally got robotic knee replacement at Marengo Asia Hospitals. Dr. Ashok Rajgopal is truly the best in the field. I was walking within 24 hours of surgery! The physiotherapy team was fantastic, and I am now pain-free for the first time in 10 years.', rating: 5, featured: false },
    { patient: 'Abdul Karim', location: 'Dhaka, Bangladesh', content: 'I came to Marengo Asia Hospitals for prostate cancer treatment. The robotic surgery by Dr. Sudhir Rawal was minimally invasive, and I had virtually no complications. The nursing staff was excellent, and the hospital food was surprisingly good. I highly recommend this hospital.', rating: 5, featured: false },
    { patient: 'Priya Patel', location: 'Mumbai, India', content: 'Dr. Sabhyata Gupta treated my cervical cancer with robotic-assisted radical hysterectomy. I was terrified when I got the diagnosis, but Dr. Gupta explained everything clearly and reassured me throughout. The surgery was successful, and the recovery was much easier than traditional surgery.', rating: 5, featured: false },
    { patient: 'James Okafor', location: 'Lagos, Nigeria', content: 'I chose Marengo Asia Hospitals for my kidney transplant after extensive research. The transplant team led by Dr. Rajesh Ahlawat performed a robotic kidney transplant — the first of its kind. The international patient coordinator assigned to me was incredibly helpful throughout my 3-week stay.', rating: 5, featured: true },
    { patient: 'Sunita Devi', location: 'Patna, India', content: 'My premature baby was born at just 28 weeks and weighed only 900 grams. The NICU team at Marengo Asia Hospitals Patna provided exceptional care for 6 weeks. Today, my daughter is a healthy 2-year-old. I cannot thank Dr. Nishant Verma and the neonatology team enough.', rating: 5, featured: false },
    { patient: 'Viktor Petrov', location: 'Moscow, Russia', content: 'Dr. Ambrish Mithal treated my complex thyroid condition that had been misdiagnosed for years in Russia. Within one week, he identified the issue, prescribed the right treatment, and I started feeling better within days. His expertise is unmatched.', rating: 5, featured: false },
    { patient: 'Kavita Joshi', location: 'Lucknow, India', content: 'I had IVF treatment at Marengo Asia Hospitals after 5 years of unsuccessful attempts elsewhere. The fertility team was incredibly supportive and thorough. On our second cycle, we were blessed with twins! The team made what felt impossible, possible.', rating: 5, featured: false },
  ];

  for (const testimonial of testimonials) {
    await prisma.testimonial.create({ data: testimonial });
  }
  console.log(`✅ Created ${testimonials.length} testimonials`);

  console.log('\\n🎉 Database seeded successfully!');
  console.log(`📊 Total records: ${locations.length + specialities.length + doctors.length + treatments.length + blogs.length + healthCheckups.length + careers.length + services.length + testimonials.length}`);
}

main()
  .then(async () => { await prisma.$disconnect(); })
  .catch(async (e) => { console.error(e); await prisma.$disconnect(); process.exit(1); });
